services:
  - type: web
    name: brandguard-backend
    env: python
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql+psycopg2://neondb_owner:npg_USr1i4LdjFGK@ep-aged-recipe-anw0usw4-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: NEWS_API_KEY
        value: 77eeac1302704784b73005d51328b26d
      - key: SERPAPI_API_KEY
        value: 7ef19efb326ee273c6b855a38114834429fca5d69bd83af78029c3d100a0a585
